apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-proxy
  labels:
    app: ws-proxy
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: ws-proxy
  template:
    metadata:
      labels:
        app: ws-proxy
        version: v1
    spec:
      containers:
        - name: ws-proxy
          image: santhoshtoorpu/ws-proxy:latest
          imagePullPolicy: IfNotPresent   # actually reduce pulls
          resources:
            requests:
              cpu: "300m"
              memory: "1Gi"
              ephemeral-storage: "4Gi"
            limits:
              cpu: "1500m"
              memory: "2Gi"
              ephemeral-storage: "8Gi"
          env:
            # Match your app.py variable names
            - name: KSERVE_URL
              value: "http://llama.santhosh.svc.cluster.local/openai/v1/chat/completions"
            - name: MODEL
              value: "llama3.1-8B"
            - name: PORT
              value: "8000"
            - name: PYTHONUNBUFFERED
              value: "1"

            # Make cache paths explicit and writable (align with Dockerfile)
            - name: HF_HOME
              value: "/home/appuser/.cache/huggingface"
            - name: TRANSFORMERS_CACHE
              value: "/home/appuser/.cache/huggingface"
            - name: SENTENCE_TRANSFORMERS_HOME
              value: "/home/appuser/.cache/sentence_transformers"
            - name: XDG_CACHE_HOME
              value: "/home/appuser/.cache"

          ports:
            - containerPort: 8000
              name: http
              protocol: TCP

          livenessProbe:
            tcpSocket: { port: 8000 }
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            tcpSocket: { port: 8000 }
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop: ["ALL"]

          # Optional: mount an emptyDir to persist cache across container restarts
          volumeMounts:
            - name: hf-cache
              mountPath: /home/appuser/.cache

      volumes:
        - name: hf-cache
          emptyDir:
            sizeLimit: 5Gi
